CREATE USER ivolunteer_user WITH PASSWORD 'IVOLUNTEER';

CREATE DATABASE IVOLUNTEER;

GRANT ALL PRIVILEGES ON DATABASE IVOLUNTEER TO ivolunteer_user;

GRANT CONNECT
ON DATABASE IVOLUNTEER
TO ivolunteer_user;